### ISSUE TITLE
example meteor application for this plugin is not working

### ISSUE THREAD

**Issue by amalan-shenll** [reactioncommerce/reaction-file-collections#1]
1) i pulled this repo
2) did "npm install"
3) did cd into "reaction-file-collections/example-apps/meteor-blaze-app"
4) again did "npm install"
5) then to start application i did "npm start", but got following err
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by aldeed** [comment]
@amalan-shenll In addition to `npm i` after pulling, do `npm run bootstrap` in project root. I will add better instructions to readme.
