### ISSUE TITLE
Uploading images requires a persistent HTTP connection

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-file-collections#11]
When using this package in a production environment if the upload is started but the next requests are handled by a different server, the upload fails. When using this in a round-robin hosting environment this means that uploads never work. The workaround was to enable sticky-sessions but this is not optimal for most environment.

**Comment by aldeed** [comment]
Yes, this is something I was aware of but chose not to implement immediately. The solution I envisioned was using one of the other tus stores: https://github.com/tus/tus-node-server#flexible-data-stores

https://github.com/reactioncommerce/reaction-file-collections/blob/master/packages/file-collections/src/node/TempFileStore.js#L43

This should be a separate package that exports a different `TempFileStore` class with the same methods and signatures as the existing one. That package could be in this repo, though, since it's a multi-package repo.

**Comment by trojanh** [comment]
I got the following error on browser console while uploading the image on our aws-ecs based Reaction

> Error: tus: unexpected response while uploading chunk, originated from request (response code: 404, response text: The file for this url was not found
> )

And following upload request 
>https://myreactionserver.test/assets/uploads/uploads/1b38d6b56f476c4f979d30cfe58f5e54

failed with 
> 404
> The file for this url was not found

This happens only on our ECS server and not on local.

I think the issue might be what @zenweasel mentioned. Let me know if there's any plan to fix this or any thought on using other stores as discussed above, I can work on the recommended fix.

**Comment by dhonig** [comment]
In a docker based environment such as ECS you don't really have a guarantee what load balancer will route to other than a target group.  I'm using an ALB with Fargate.  I believe the problem that @trojanh mentioned is the lack of shared temporary storage.  We've deployed using terraform. The solution is to modify our tasks definitions in the following way:  https://docs.aws.amazon.com/AmazonECS/latest/userguide/using_data_volumes.html   Once we get this done I'll report back.

**Comment by janus-reith** [comment]
Just enabling Sticky Sessions on the Load Balancer did not work for me, as the session is usually determined by cookie.
`reaction-file-collections` is using `tus-js-client` to handle the upload in the browser, which has an optional parameter `withCredentials`that defaults to false.

**Comment by deepakkhandelwalgit** [comment]
I am facing issue when uploading image from browser. This is only happening in case pf production build. My project is setup in EKS environment.

I am getting following error on server

error ENOENT : no such file or directory, open uploads/31362fdhdh45hssa1dj4
