### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-file-collections#18]
In order to remove some of the snyk ignore rules in the reactioncommerce/reaction repo we need to publish the latest release of file-collections to npm

**Comment by spencern** [comment]
@ticean @griggheo @aldeed This was something that Eric and I ran into and it seems to be an issue with either an invalid npm or github key causing the deploy step to fail.
See: https://circleci.com/gh/reactioncommerce/reaction-file-collections/90 
The step passes CI, but internally fails to publish with an error. Open the "Publish to NPM and Github" step to see.
```
(node:92) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: ERROR: The key you are authenticating with has been marked as read only.
```

**Comment by aldeed** [comment]
I'm 99% sure it's referring to `GH_TOKEN` because there's an earlier step involving checking the NPM token permissions, which seems to pass. The `GH_TOKEN` that we have for that CI context works fine on other repos that use semantic-release directly, but this repo uses Lerna, which is another layer on top of semantic-release with different requirements. We do need to use Lerna to successfully publish since there are multiple packages in the repo, with dependencies on each other.

**Comment by ticean** [comment]
@aldeed do you think the problem is that Lerna is expecting an ENV by another name? You mention `GH_TOKEN` If so, you could [assign the value to another ENV var in CircleCI](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-job), using the name Lerna expects. Example: 

```yaml
jobs:
  job_name:
    # ...
    environment:
      GITHUB_TOKEN: $GH_TOKEN
```

**Comment by spencern** [comment]
@ticean It seems to be finding the token because the warning specifies: `The key you are authenticating with has been marked as read only`

**Comment by aldeed** [comment]
@ticean Is this helpful? https://github.com/lerna/lerna/issues/1524

**Comment by ticean** [comment]
The Github token in the CircleCI context has permissions to write - it has full repository admin. Github publishing is working on other projects.

> `The key you are authenticating with has been marked as read only`

A comment in the posted issue claims it was a problem with the SSH key. CircleCI creates a read-only SSH key for checkout. I don't see config docs in the Lerna project. Can you configure Lerna to push with https protocol and token auth?

**Comment by ticean** [comment]
I added an SSH key to the CircleCI publishing context. You could possibly use that in the publish step but you'll need to indirectly force git to use the key. You should be able to do that by setting the `GIT_SSH` var in the Lerna deploy command. `GIT_SSH=<ssh-wrapper-here> lerna <...>`

[This guide](https://blog.tankywoo.com/2014/04/15/git-use-specified-ssh-key.html) looks decent. The wrapper could get the key value from the CircleCI context and construct the `ssh` command.
