### ISSUE TITLE
Limit RemoteUrlWorker concurrency

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction-file-collections#21]
I created a GraphQL Mutation that takes a product id and url, which then uses `FileRecord.fromUrl` to fetch the image from that url and insert it into MediaRecords.

`setUpFileCollections` in `/imports/plugins/core/files/server/no-meteor/setUpFileCollections.js` defines a `transformWrite` function that uses sharp as stream to create the different sized images.

I am trying to use this to batch add/remove images, but this runs out of memory after around 8 images were processed.

This is clearly related to the resource intense conversion process, If I remove some of the stores for image sizes the issue disappears.

I tried to enforce a delay between executions, but this is an ugly solution and also was unreliable.

Is there any way to limit the concurrency of the transformWrite execution?

I want the API to accept a few hundred incoming files, and save them initially with `remoteUrl`,
but limit the execution of the transformWrite operations to be sequentially.

**Update: RemoteUrlWorker is the cause, nothing wrong with transformWrite itself.**

**Comment by janus-reith** [comment]
Error could be somewhere around here:
https://github.com/reactioncommerce/reaction-file-collections/blob/7bb02ce64efac3086b61bf0834993a42737df194/packages/file-collections/src/node/RemoteUrlWorker.js#L31

I think I want to run this sequentially instead.

**Comment by rosshadden** [comment]
I don't think something like this should ever be parallel, or at least should be capped to a certain (configurable) batch size. Good find!

**Comment by janus-reith** [comment]
I prepared a qucik and simple demonstration on how this could be fixed:
https://github.com/janus-reith/reaction-file-collections/commit/0d18a2d350982d69d919ac43f8a6224350f40c6c

I can now sucessfully add hundres of documents to Media collection, and RemoteUrlWorker will process them in order.

However, I feel like there must be a better solution to this.

- All docs are stored in Memory in the `observedEntries` array. Not sure about scalability here, altough this docs are quite small. On the other hand, just saving the id and pulling each document by id from the db again also seems inefficient.

- I am using `isProcessing` as a boolean to determine if the method `processObserved` is already running, to prevent parallel execution. It is set to true before starting the for...of loop, and to false when that finished, Im not sure if that will always work, or if there is a possibility of something s lipping through.

- I am not removing entries from `observedEntries` after processing them, to not mess up index position of the iterator. I did not notice any duplicate execution yet, but wonder if thi could lead to issues.

**Comment by trojanh** [comment]
Hi @janus-reith , I got following error recently while bulk image importing using 
https://github.com/reaction-contrib/meteor-connector-shopify connector, 

```
Error: Error in RemoteUrlWorker remote URL storage loop:
reaction_1  |     at RemoteUrlWorker._callee2$ (/opt/reaction/src/node_modules/@reactioncommerce/file-collections/dist/node/RemoteUrlWorker.js:90:19)
```

I think the issue you mentioned here might be related to this. Will you PR fix this as well by any chance?

**Comment by janus-reith** [comment]
As discussed in the chat, probably not, as your workload is already split into separate Jobs, and your server doesn't crash from being overloaded. But you still might give it a try.

**Comment by trojanh** [comment]
Sure @janus-reith thanks will give it a try.

**Comment by rosshadden** [comment]
I'm not a fan of all of the docs being in memory, but this is still a great first step and that caveat doesn't detract from that.

**Comment by janus-reith** [comment]
Changing that to just use the id and fetch the document on each run should be really simple and I'm starting to see an general advantage here. Lets say image 4 out of 100 is processed and I change the data of image 50: When image 50 is reached, it would still use the doc from memory. Probably not a common scenario, but it should be possible.

I wonder if another good option would be to make use of the Job collection?
While this would bring in an additional dependency here, it would give more valueable insights as this is a currently unsupervised process that can be the cause of lots of errors.
e.g. I want to be able to see which doc/image failed out of thousands.

**Comment by janus-reith** [comment]
I just implemented a conversion process that schedules Jobs for every observed new doc.

My proposal:

1. reaction `files` core plugin creates a Job that converts Images. That will trigger `_handleRemoteURLAdded` of `RemoteUrlWorker` https://github.com/reactioncommerce/reaction-file-collections/blob/7bb02ce64efac3086b61bf0834993a42737df194/packages/file-collections/src/node/RemoteUrlWorker.js#L55
To be able to use that inside of reaction, we export the instance of it that we create here: https://github.com/reactioncommerce/reaction/blob/74f894594ff090390723504b05c890ec8d1a70a7/imports/plugins/core/files/server/fileCollections.js#L77

2. When a new instance of `RemoteUrlWorker` is created, it gets passed a function `onNewDocument` that it calls here instead of directly calling `_handleRemoteURLAdded`: https://github.com/reactioncommerce/reaction-file-collections/blob/7bb02ce64efac3086b61bf0834993a42737df194/packages/file-collections/src/node/RemoteUrlWorker.js#L39

3. This callback in `fileCollections.js` would then create a new Job to convert that image. https://github.com/reactioncommerce/reaction/blob/develop/imports/plugins/core/files/server/fileCollections.js#L77 

This would keep the Job logic out this package. We could also drop my other PR regarding `appEvents` as now there is a Job in core code that knows when the conversion actually finished which could then emit an event from there.

**Comment by spencern** [comment]
Thanks for continuing to follow-up on this @janus-reith 

It's important that this package and any job runner that we have not be coupled. I'm glad you've already taken that into consideration. We're planning to migrate away from the existing Job scheduler/runner that we have as the current implementation is Meteor dependent. @aldeed has been looking at that process a bit. There's a chance that a new job runner would share an API and be compatible, but I don't know that we've gotten far enough in the process to know for certain. 

@aldeed will you take a look at this when you get a chance?

**Comment by aldeed** [comment]
@janus-reith I agree with Spencer. Your proposal is in step with general plans for Reaction. The caveat is that all of the file-collections packages do not currently assume a Reaction environment (you can use them in any Node/Meteor app) and should ideally stay that way.

So:
- Yes, `onNewDocument` (or maybe `onNewFileRecord`?) to keep job logic out of the package
- Make `_handleRemoteURLAdded` public (remove `_` prefix) since workers will need to call it
- Maybe if `onNewDocument` isn't provided keep the old behavior so that it stays backward compatible?

Let us know when one of your PRs is ready with this pattern, or which PRs are still needed for this approach.

**Comment by janus-reith** [comment]
Sounds good. Will prepare a PR with the aforementioned features and a fallback option if `onNewFileRecord` is missing.

**Comment by janus-reith** [comment]
Today I wanted to implement this finally, but noticed that in https://github.com/reactioncommerce/reaction/commit/4a3c8cae1efa5ef6ec5dfc3aa89e0334e7327bc9 the way the  RemoteUrlWorker instance is set up changed: [imports/plugins/core/files/server/fileCollections.js#L22](https://github.com/reactioncommerce/reaction/blob/1f074b502d8fc36427123f1413264b19a74a6340/imports/plugins/core/files/server/fileCollections.js#L22)

Previously I could just export the created `remoteUrlWorker` Instance from there.
Now that file exports a function `meteorFileCollectionStartup`, which is called from `startNodeApp`.

I'm a bit stuck here, as I'm not really sure how to access the instance of remoteUrlWorker in a clean way now.

While I coud export it from `startNodeApp`, that seems a bit weird.

I need access to the remoteUrlWorker instance in order to call its `handleRemoteURLAdded` function from a job.

**Comment by janus-reith** [comment]
I could also create a separate Class in the files plugin that is empty upon startup, and exports a function to create the instance of remoteUrlWorker. This function could be called from the `meteorFileCollectionStartup` to set up the remoteUrlWorker instance. That Class could export another function to give access to the functions of the `RemoteUrlWorker` instance which I could then use when processing the Jobs.

That solution also seems a bit like weird overhead.

Third option could be to turn [imports/plugins/core/files/server/fileCollections.js#L22](https://github.com/reactioncommerce/reaction/blob/1f074b502d8fc36427123f1413264b19a74a6340/imports/plugins/core/files/server/fileCollections.js#L22) into a class instead that has a sartup function and gives access to the `RemoteUrlWorker` .

Am I missing something here that would be cleaner?

**Comment by janus-reith** [comment]
Is there a fundamental reason to call `meteorFileCollectionStartup` in `startNodeApp` of the core plugin now?

Else I would move that back to a startup function of the `files` plugin.
Apart from that seeming more like the right place for it, it would give me the benefit of having a place where I could export from that function, so I can continue with this issue.

@aldeed I believe you made these changes in commit https://github.com/reactioncommerce/reaction/commit/4a3c8cae1efa5ef6ec5dfc3aa89e0334e7327bc9, any suggestions here? Are there any blockers, like `startNodeApp` running at an earlier point than the plugin startup and therefore being a requirement or something similar?

**Comment by aldeed** [comment]
@janus-reith I had to dig into this to remind myself why it's this way.

First, it should _not_ be calling `meteorFileCollectionsStartup` in `startNodeApp`, but that was done as a temporary solution.

The problem is that the no-meteor `setUpFileCollections` does not _quite_ do everything that the Meteor file does. So the issue is that we haven't yet fully de-Meteorized this plugin. The two main differences I see are:
- Meteor file creates `MeteorFileCollection` instead of `MongoFileCollection`
- Meteor file creates `RemoteUrlWorker` instance and no-meteor file does not

The reason RemoteUrlWorker isn't created when running outside of Meteor is because that class is dependent on Meteor. From the package docs:

> All provided FileCollections must be MeteorFileCollections rather than MongoFileCollections because Meteor's observe API is used. A variation of this could be created to use polling or some other method for detecting waiting remote URL inserts.

Since we're very close to removing Meteor from the API codebase, I think your solution should probably create an alternative version of `RemoteUrlWorker` that doesn't need Meteor. It could poll, but Mongo 3.6+ now has change streams, which should be a perfect replacement for Meteor's observe: http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#watch

After that change and adding `RemoteUrlWorker` create + start to the no-meteor startup function, I _think_ it would be safe to remove the `meteorFileCollectionsStartup` call and only `imports/plugins/core/files/server/no-meteor/startup.js` will be used regardless of whether it's a Meteor environment.

I believe that will solve your access problems, right?

**Comment by aldeed** [comment]
And @janus-reith, if you don't want to PR this package with a no-meteor `RemoteUrlWorker`, I would just put equivalent code directly in the files plugin startup function. Essentially just watch the collection and create jobs in the change handler I think.

**Comment by janus-reith** [comment]
Okay, will look into this.
And yes this would solve my problems of accessing the exports.

I thought it could just work to keep `meteorFileCollectionsStartup` out of `no-meteor` to indicate that it still needs meteor, but still import it from `no-meteor/startup` to have access to its output.

But removing the Meteor dependencies is the better long term solution for sure.
( I had a use case where I completely separated the files plugin with the conversion of the images into a separate container, this will probably become easier then aswell as I currently kept a lot of core code overhead )

You only mentioned `RemoteUrlWorker`, being necessary, what about `TempFileStoreWorker` ? 
This seems to use the same observe pattern, so would I need to rewrite that aswell I guess.

When you say I could put the `RemoteUrlWorker` code in the startup function of a plugin, do you mean to copy it over from my PR to this repo then or to actually merge it that way to core?

Because what I was currently doing was to test that in the core plugin, and if everything works I copied it over to my `reaction-file-collections` fork.

**Comment by janus-reith** [comment]
Implementing the changeStream for the `RemoteUrlWorker` and thereby demeteorizing it was pretty straight forward.

TempFileStoreWorker however seems to be a bit tricky.
It observes added and removed documents that have a `tempStoreId` on `original`.
If one is removed, it takes the `tempStoreId` and calls `tempStore.deleteIfExists`.

The problem now is, that in contrast to the `observe` pattern of the Meteor Collection the Mongo Collection Change Stream doesn't return the document if the `operationType` is delete.

However, It seems to me like there is no actual use case for that remove event?
It would trigger when a document that has a `tempStoreId` is removed from the Media Collection.
AFAIK we don't remove entries from there at all.

**Comment by janus-reith** [comment]
Done.

Created a PR for file-collections here: https://github.com/reactioncommerce/reaction-file-collections/pull/28

And a PR in the reaction repo here: https://github.com/reactioncommerce/reaction/pull/5321
The second PR mainly targets the usage of jobs in the main repo, but also includes the refactored versions of `RemoteUrlWorker` and `TempFileStoreWorker` for testing purpouses.

**Comment by aldeed** [comment]
Wow, thanks @janus-reith! I'll try to look at this this week. I did mean that you could merge it that way into core, but if it can be updated in this package then that's nice for anyone using this package outside of Reaction env.
