### ISSUE TITLE
Meteor Example app

### ISSUE THREAD

**Issue by chrispotter** [reactioncommerce/reaction-file-collections#29]
Is `example-apps/meteor-blaze-app` still relevant? 

Is it something we should remove with the introduction of new reaction versions?

**Comment by aldeed** [comment]
@chrispotter Still useful for now as a quick way to test that the packages work, and work within Meteor apps. It may be good to add another example app that uses some other framework.

**Comment by loan-laux** [comment]
Is this example app still working though? I just freshly cloned the repo and am getting `Method 'FileCollection/INSERT/Images' not found [404]` when uploading an image. Am I missing something?

**Comment by aldeed** [comment]
@loan-laux I tested with it when I recently did https://github.com/reactioncommerce/reaction-file-collections/commit/8066d644e7913da89fdb8e0e3f5439324f98a87c and it was working for me. Possibly something changed after that? Can you file a new issue with the full reproduction steps?

**Comment by loan-laux** [comment]
@aldeed I explained and fixed my issue in PR #33. Let me know if that's the right approach of if I'm missing something obvious here.
