### ISSUE TITLE
endpoint.startsWith("/") in FileRecord.js enforces relative Path

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction-file-collections#34]
`set uploadEndpoint` in 
https://github.com/reactioncommerce/reaction-file-collections/blob/0711e11d5d632c37c74b5ec293db8fc5df297a44/packages/file-collections/src/common/FileRecord/FileRecord.js#L94
and 
`downloadEndpointPrefix` in
https://github.com/reactioncommerce/reaction-file-collections/blob/0711e11d5d632c37c74b5ec293db8fc5df297a44/packages/file-collections/src/common/FileRecord/FileRecord.js#L104

Will add "/" to the start of the url if that is not what it starts with already.

Now that the Admin and API are separated that won't work out, as these paths won't be relative anymore.
This can be worked around by starting an url with "//" while omitting the protocol, but would e.g break if some setup would use https for the client initiating the upload, while the endpoint recieving it would only use http for some reason.

Apart from that, as this package was meant to be general purpouse, I don't see any advantage in this restriction.

**Comment by aldeed** [comment]
I don't fully understand how either of these would matter. Splitting into two projects would only mean we need to ensure `FileRecord.absoluteUrlPrefix` is being set properly in both projects.

The main reason it checks the slashes for the prefixes is because `FileRecord.absoluteUrlPrefix` is combined with the download or upload endpoint prefixes, and we need to know we won't double any slashes when that happens. That hasn't changed.

**Comment by janus-reith** [comment]
The issue here for me was, that although `absoluteUrlPrefix` was set in the client sending the data to the url were the recieiving part sits, the path were the Upload data was send to still was relative to the current URL, which would be the one of the Sending part.
(e.g with the admin ui on localhost:3100 and the API Endpoint on localhost:3000, the client part of a created Filerecord would always try uploading to localhost:3100/upload.

Maybe that is the actual issue here, if those paths are always expected to be relative, the current path logic could be kept, but absoluteUrlPrefix should be used then.

Setting `FileRecord.absoluteUrlPrefix = "http://localhost:3000";` would still result in a relative path being used in the client, localhost:3100/assets/uploads in my case.

**Comment by aldeed** [comment]
@janus-reith I meant to update it in the client code.

Change `FileRecord.absoluteUrlPrefix = DomainsMixin.absoluteUrl();` to `FileRecord.absoluteUrlPrefix = "http://localhost:3000";` (or from ENV variable) in `imports/plugins/core/files/client/index.js` in Reaction Admin. Is this what you did?

**Comment by janus-reith** [comment]
Yes. exactly - Without effect apparently.
Instead I set both endpoints to "//localhost:3000/uploads/" / "//localhost:3000/files" for now.

Just wondering, I think you would've run into something similar when detaching the Admin Backend from the API?
